
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorlexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 44;
  public static final int NUMERO = 2;
  public static final int SHORT = 12;
  public static final int OP_ATRIBUCION = 35;
  public static final int CONST = 20;
  public static final int CHAR = 9;
  public static final int OP_NEGACION = 37;
  public static final int CASE = 19;
  public static final int DOUBLE = 11;
  public static final int RESTA = 29;
  public static final int CONTINUE = 21;
  public static final int LLAVEDER = 41;
  public static final int INT = 8;
  public static final int FOR = 17;
  public static final int WRITE = 43;
  public static final int CORCHETEIZQ = 45;
  public static final int IDENTIFICADOR = 26;
  public static final int IGUAL = 27;
  public static final int NUMERO_OCT = 3;
  public static final int OP_BOOLEANO = 34;
  public static final int SUMA = 28;
  public static final int IF = 13;
  public static final int OP_RELACIONAL = 33;
  public static final int PARIZQ = 38;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int NUMERO_HEX = 4;
  public static final int error = 1;
  public static final int COMA = 48;
  public static final int MODULO = 49;
  public static final int BREAK = 18;
  public static final int VOID = 25;
  public static final int ERROR = 50;
  public static final int PCOMA = 47;
  public static final int SWITCH = 24;
  public static final int LITERAL = 6;
  public static final int CORCHETEDER = 46;
  public static final int ELSE = 14;
  public static final int READ = 42;
  public static final int OP_LOGICO = 32;
  public static final int WHILE = 16;
  public static final int LLAVEIZQ = 40;
  public static final int DEFAULT = 22;
  public static final int FLOAT = 10;
  public static final int LONG = 7;
  public static final int OP_INCDEC = 36;
  public static final int PARDER = 39;
  public static final int DIVISION = 31;
  public static final int NUMERO_FLOAT = 5;
  public static final int DO = 15;
  public static final int MULTIPLICACION = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "NUMERO_OCT",
  "NUMERO_HEX",
  "NUMERO_FLOAT",
  "LITERAL",
  "LONG",
  "INT",
  "CHAR",
  "FLOAT",
  "DOUBLE",
  "SHORT",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "BREAK",
  "CASE",
  "CONST",
  "CONTINUE",
  "DEFAULT",
  "RETURN",
  "SWITCH",
  "VOID",
  "IDENTIFICADOR",
  "IGUAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "OP_LOGICO",
  "OP_RELACIONAL",
  "OP_BOOLEANO",
  "OP_ATRIBUCION",
  "OP_INCDEC",
  "OP_NEGACION",
  "PARIZQ",
  "PARDER",
  "LLAVEIZQ",
  "LLAVEDER",
  "READ",
  "WRITE",
  "DOSPUNTOS",
  "CORCHETEIZQ",
  "CORCHETEDER",
  "PCOMA",
  "COMA",
  "MODULO",
  "ERROR"
  };
}

